global:
  scrape_interval: 15s  # Recolecta las métricas cada 15 segundos

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:3000']  # La dirección de tu aplicación en WSL

