apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: demo-api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      serviceAccountName: api-user
      containers:
        - name: api
          image: edeljose/api-k8s-demo1:latest
          ports:
            - containerPort: 3000
          env:
            - name: JAEGER_AGENT_HOST
              value: "localhost"
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SERVICE_NAME
              value: "api-demo"
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.53
          args: ["--reporter.grpc.host-port=jaeger-collector.observability.svc.cluster.local:14250"]
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP

