apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: demo-api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      serviceAccountName: api-user
      containers:
        - name: api
          image: edeljose/api-k8s-demo1:latest
          ports:
            - containerPort: 3000

