apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      serviceAccountName: api-user
      containers:
        - name: api
          image: edeljose/api-k8s-demo1:latest
          ports:
            - containerPort: 3000

